### ISSUE TITLE
How can i download the pacakge for this import "import oracle_crop" 

### ISSUE THREAD

**Issue by ahmed024** [darth-c0d3r/black_box_attacks#2]
Hi, I keep getting this error. 
'ModuleNotFoundError: No module named 'oracle crop' could be found.' 
I attempted to install this package using pip, but it does not exist or  i have the name wrong. Could you please tell how to install this package? Thanks.

**Comment by meghu** [comment]
@darth-c0d3r I have the same issue and tried looking at where this file can be but couldn't locate. Can you please help or guide on how to import this file. Thank you.
